<a href="https://colab.research.google.com/github/Shaileshps21/pytorch-/blob/main/pytorch_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NN modules

Plan of Action
1. Improvements
2. The nn module
3. The torch.optim module

Improvements
1. Building the neural network using nn module
2. Using built-in activation function
3. Using built-in loss function
4. Using built-in optimizer


Create a basic model using nn modules

In [7]:
# create model class
import torch
import torch.nn as nn
!pip install torchinfo
from torchinfo import summary

In [8]:
class Model(nn.Module):
  def __init__(self , num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid= nn.Sigmoid()

  def forward(self, features): # Renamed from forward_pass to forward
    output = self.linear(features) #it is same as y=wx+b
    output = self.sigmoid(output)
    return output

In [9]:
# create dataset
features = torch.rand(10,5)
features

model = Model(features.shape[1])
model(features) # Changed to call the model instance directly

tensor([[0.4558],
        [0.4397],
        [0.4505],
        [0.5396],
        [0.4486],
        [0.4601],
        [0.4989],
        [0.4451],
        [0.4740],
        [0.4656]], grad_fn=<SigmoidBackward0>)

In [10]:
print(model.linear.bias)
print(model.linear.weight)
print()

summary(model, input_size=(10,5))

Parameter containing:
tensor([-0.3212], requires_grad=True)
Parameter containing:
tensor([[ 0.3020, -0.0627, -0.1576,  0.1799,  0.0858]], requires_grad=True)



Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

now, we will create a new neural network with the hidden weights

In [11]:
class Model(nn.Module):

  def __init__(self, num_features):
    super().__init__()
    self.linear1 = nn.Linear(num_features, 3)
    self.relu    = nn.ReLU()
    self.linear2 = nn.Linear(3, 1) # Corrected: input to linear2 is 3 features
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear1(features) # Output is (batch_size, 3)
    out = self.relu(out)         # Pass output from linear1 to relu
    out = self.linear2(out)      # Pass output from relu to linear2
    out = self.sigmoid(out)      # Pass output from linear2 to sigmoid
    return out

In [12]:
# create dataset
features = torch.rand(10,5)
features

model = Model(features.shape[1])
model(features) # Changed to call the model instance directly

# model parameters
print(model.linear1.bias)
print(model.linear1.weight)
print()

print(model.linear2.bias)
print(model.linear2.weight)

Parameter containing:
tensor([ 0.3351, -0.1870,  0.1013], requires_grad=True)
Parameter containing:
tensor([[-0.4181, -0.0809, -0.0542, -0.2685, -0.2258],
        [-0.0565, -0.1074,  0.3234,  0.1304, -0.3313],
        [-0.0700, -0.1804, -0.0579, -0.1979, -0.1706]], requires_grad=True)

Parameter containing:
tensor([0.5289], requires_grad=True)
Parameter containing:
tensor([[ 0.4288, -0.3657,  0.1592]], requires_grad=True)


lets use, sequential containers

In [13]:
class Model(nn.Module):

  def __init__(self, num_features):
    super().__init__()
    self.network = nn.Sequential(
      nn.Linear(num_features, 3),
      nn.ReLU(),
      nn.Linear(3, 1),
      nn.Sigmoid()
    )

  def forward(self, features):
    out = self.network(features)
    return out