<a href="https://colab.research.google.com/github/Shaileshps21/pytorch-/blob/main/pytorch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TENSORS

In [2]:
import torch
import numpy as np
print(torch.__version__)

2.9.0+cu126


In [3]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU is not available")

GPU is available
Using GPU: Tesla T4


CREATING A TENSOR

In [4]:
# using empty
a = torch.empty(2,3)
print(type(a))
print(a)
print()

# using zeros
b = torch.zeros(2,3)
print(type(b))
print(b)
print()

# using ones
c = torch.ones(2,3)
print(type(c))
print(c)
print()

# using seed
d = torch.rand(2,3)
print(type(d))
print(d)
print()


<class 'torch.Tensor'>
tensor([[0.0000e+00, 0.0000e+00, 4.2039e-45],
        [0.0000e+00, 4.2039e-45, 7.0065e-45]])

<class 'torch.Tensor'>
tensor([[0., 0., 0.],
        [0., 0., 0.]])

<class 'torch.Tensor'>
tensor([[1., 1., 1.],
        [1., 1., 1.]])

<class 'torch.Tensor'>
tensor([[0.9213, 0.2269, 0.1909],
        [0.9810, 0.7783, 0.0149]])



In [5]:
# using manual seed--- to give the same random value each time
torch.manual_seed(100)
e = torch.rand(2,3)
print(e)
print()

# using tensor
f = torch.tensor([[1,3,5],[4,2,6]])
print(type(f))
print(f)
print()


# other ways
print("using arange-->" , torch.arange(0,10,2))

print("using linspace-->" , torch.linspace(0,10, 6))

print("using eye-->" , torch.eye(5))

print("using full-->" , torch.full((3,3) ,5))


tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

<class 'torch.Tensor'>
tensor([[1, 3, 5],
        [4, 2, 6]])

using arange--> tensor([0, 2, 4, 6, 8])
using linspace--> tensor([ 0.,  2.,  4.,  6.,  8., 10.])
using eye--> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full--> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


TENSOR SHAPE

In [6]:
X = torch.tensor([[1,3,5],[2,5,6]])
print(X.shape)


y = torch.tensor([[1,3,5,7],[2,4,6,8]])
print(y.shape)
print(y)

torch.Size([2, 3])
torch.Size([2, 4])
tensor([[1, 3, 5, 7],
        [2, 4, 6, 8]])


To create a tensor which looks like someone created earlier

In [7]:
torch.empty_like(y)

torch.zeros_like(y)

torch.ones_like(y)

# torch.rand_like(y) #will create a error
torch.rand_like(y , dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080, 0.1180],
        [0.1217, 0.7356, 0.7118, 0.7876]])

TENSOR DATA TYPES

In [8]:
print(y.dtype)

# assign data types
z = torch.tensor([1.0, 2.5, 3.0 , 4.1] , dtype=int)
print(z)

z = torch.tensor([1.0, 2.0, 3.0 , 4.0] , dtype=float)
print(z)

# using to() method to convert data types
z.to(torch.int)
print(z)

torch.int64
tensor([1, 2, 3, 4])
tensor([1., 2., 3., 4.], dtype=torch.float64)
tensor([1., 2., 3., 4.], dtype=torch.float64)


MATHEMATICAL OPERATIONS

In [9]:
x = torch.rand(2,2)
print(x)


# scalar operation
# addition
print(x+2)
# subtraction
print(x-3)
# multiplication
print(x*2)
# division
print(x/2)
# int division
print(x//2)


tensor([[0.4183, 0.9014],
        [0.9969, 0.7565]])
tensor([[2.4183, 2.9014],
        [2.9969, 2.7565]])
tensor([[-2.5817, -2.0986],
        [-2.0031, -2.2435]])
tensor([[0.8366, 1.8028],
        [1.9938, 1.5130]])
tensor([[0.2092, 0.4507],
        [0.4984, 0.3783]])
tensor([[0., 0.],
        [0., 0.]])


In [10]:
# element wise operations
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)
print()

# add
print(a+b)
# subtraction
print(a-b)
# mulltiplication
print(a*b)
# division
print(a/b)

tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])
tensor([[0.4440, 0.9478, 0.7445],
        [0.4892, 0.2426, 0.7003]])

tensor([[0.6679, 1.2502, 0.9229],
        [1.3130, 0.7983, 1.6774]])
tensor([[-0.2201, -0.6455, -0.5661],
        [ 0.3346,  0.3132,  0.2767]])
tensor([[0.0994, 0.2866, 0.1328],
        [0.4030, 0.1348, 0.6842]])
tensor([[0.5042, 0.3190, 0.2397],
        [1.6841, 2.2912, 1.3951]])


In [11]:
# reduction operations
e = torch.randint(size=(2,3) , low =0 , high=10 , dtype=torch.float32)
print(e)

# sum
torch.sum(e)
# sum along col
torch.sum(e, dim=0)
# sum along row
torch.sum(e, dim=1)

# mean
torch.mean(e)
# min, max, product, standard deviation
torch.argmax(e)
torch.argmin(e)

tensor([[7., 0., 0.],
        [9., 5., 7.]])


tensor(1)

In [12]:
# matrix multiplication
f = torch.randint(size=(2,3) , low=0 , high= 10 , dtype = torch.float32)
g = torch.randint(size=(3,2) , low=5 , high= 10 , dtype = torch.float32)

print(f)
print(g)
print()
# matrix multiplication
print(torch.matmul(f,g))

# transpose
torch.transpose(f,0,1)

# comparison operator---- same as in other languages

# special operators
torch.sqrt(f)
torch.sigmoid(f)
torch.softmax(f, dim=0)
torch.relu(f)

tensor([[3., 9., 4.],
        [0., 5., 7.]])
tensor([[5., 9.],
        [9., 7.],
        [5., 9.]])

tensor([[116., 126.],
        [ 80.,  98.]])


tensor([[3., 9., 4.],
        [0., 5., 7.]])

INPLACE OPERATIONS

In [13]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)
print()

# if i use m+n to perform the addition then it will generate a new memory to store the result, so we use add_ fn
# print(m.add_(n))

m.sub_(n)

m.relu_()

tensor([[0.9051, 0.5989, 0.4450],
        [0.7278, 0.4563, 0.3389]])
tensor([[0.6211, 0.5530, 0.6896],
        [0.3687, 0.9053, 0.8356]])



tensor([[0.2839, 0.0458, 0.0000],
        [0.3591, 0.0000, 0.0000]])

COPYING A TENSOR

In [14]:
a = torch.rand(2,3)
print(a)

b = a
print(b)
print()

a[0][0]=20
print(a)
print(b)

print(id(a))
print(id(b))


c= a.clone()
print(c)
print()

a[0][0]=12
print(a)
print(c)

print(id(a))
print(id(c))

tensor([[0.3039, 0.6726, 0.5740],
        [0.9233, 0.9178, 0.7590]])
tensor([[0.3039, 0.6726, 0.5740],
        [0.9233, 0.9178, 0.7590]])

tensor([[20.0000,  0.6726,  0.5740],
        [ 0.9233,  0.9178,  0.7590]])
tensor([[20.0000,  0.6726,  0.5740],
        [ 0.9233,  0.9178,  0.7590]])
139384560053104
139384560053104
tensor([[20.0000,  0.6726,  0.5740],
        [ 0.9233,  0.9178,  0.7590]])

tensor([[12.0000,  0.6726,  0.5740],
        [ 0.9233,  0.9178,  0.7590]])
tensor([[20.0000,  0.6726,  0.5740],
        [ 0.9233,  0.9178,  0.7590]])
139384560053104
139388587298320


TENSOR OPERATIONS ON GPU

In [16]:
torch.cuda.is_available()

True

In [19]:
device = torch.device('cuda')

torch.rand((2,3) , device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [24]:
# moving an existing tensor to gpu
a = torch.rand(2,3)
a

b = a.to(device)
print(b)
b+5

tensor([[0.4393, 0.2243, 0.8935],
        [0.0497, 0.1780, 0.3011]], device='cuda:0')


tensor([[5.4393, 5.2243, 5.8935],
        [5.0497, 5.1780, 5.3011]], device='cuda:0')

RESHAPING TENSORS

NUMPY AND PYTORCH

In [28]:
a = torch.tensor([1,2,3])
print(a)
print(type(a))

tensor([1, 2, 3])
<class 'torch.Tensor'>


In [29]:
b = a.numpy()
print(b)
print(type(b))

[1 2 3]
<class 'numpy.ndarray'>


In [31]:
c = np.array([1,4,7])
print(c)

d=torch.from_numpy(c)
print(d)
print(type(d))

[1 4 7]
tensor([1, 4, 7])
<class 'torch.Tensor'>
