<a href="https://colab.research.google.com/github/Shaileshps21/pytorch-/blob/main/pytorch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TENSORS

In [ ]:
import torch
import numpy as np
print(torch.__version__)

2.9.0+cpu


In [ ]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU is not available")

GPU is not available


CREATING A TENSOR

In [ ]:
# using empty
a = torch.empty(2,3)
print(type(a))
print(a)
print()

# using zeros
b = torch.zeros(2,3)
print(type(b))
print(b)
print()

# using ones
c = torch.ones(2,3)
print(type(c))
print(c)
print()

# using seed
d = torch.rand(2,3)
print(type(d))
print(d)
print()


<class 'torch.Tensor'>
tensor([[ 2.0702e-14,  0.0000e+00,  1.3476e-14],
        [ 0.0000e+00, -2.9839e+02,  4.5342e-41]])

<class 'torch.Tensor'>
tensor([[0., 0., 0.],
        [0., 0., 0.]])

<class 'torch.Tensor'>
tensor([[1., 1., 1.],
        [1., 1., 1.]])

<class 'torch.Tensor'>
tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])



In [ ]:
# using manual seed--- to give the same random value each time
torch.manual_seed(100)
e = torch.rand(2,3)
print(e)
print()

# using tensor
f = torch.tensor([[1,3,5],[4,2,6]])
print(type(f))
print(f)
print()


# other ways
print("using arange-->" , torch.arange(0,10,2))

print("using linspace-->" , torch.linspace(0,10, 6))

print("using eye-->" , torch.eye(5))

print("using full-->" , torch.full((3,3) ,5))


tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

<class 'torch.Tensor'>
tensor([[1, 3, 5],
        [4, 2, 6]])

using arange--> tensor([0, 2, 4, 6, 8])
using linspace--> tensor([ 0.,  2.,  4.,  6.,  8., 10.])
using eye--> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full--> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


In [ ]:
print("hell")

hell
